---
title: "Data Science Resources for R and Python"
author: "Marc Teunis, PhD"
date: "9/6/2021"
output: 
  rmdformats::downcute:
    self_contained: TRUE
    number_sections: TRUE
    keep_md: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Software

 - [R - CRAN](https://cran.r-project.org/)
 - [RStudio](https://www.rstudio.com) 
 - [Docker](https://www.docker.com/)
 - [Visual Studio Code](https://code.visualstudio.com/)
 - [Git](https://git-scm.com/downloads)
 - [Anaconda](https://www.anaconda.com/)
 - [Python IDE](https://www.jetbrains.com/)
 
 
# Getting started with R

 - [R for Data Science {print book / ebook / bookdown website}](https://r4ds.had.co.nz/)
 - [R Online learning community](https://www.youtube.com/channel/UCCaChdLMTYMxyawR_Qf-kYA)
 - [Code Academy](https://www.codecademy.com/search?query=R)
 - [The Art of Data Science](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwi8-_6_7enyAhVCQhoKHdbJBPYQFnoECAkQAQ&url=http%3A%2F%2Fbedford-computing.co.uk%2Flearning%2Fwp-content%2Fuploads%2F2016%2F09%2Fartofdatascience.pdf&usg=AOvVaw3xnbumdj1d5izhoC3DKS5T)
 - [RStudio](https://education.rstudio.com/learn/)
 - [DBeaver - IDE for databases](https://dbeaver.io/)
 
## Getting started with Python

 - [Udemy](https://www.udemy.com/course/python-the-complete-python-developer-course/?gclid=Cj0KCQjw-NaJBhDsARIsAAja6dPRbiLa-EYSjw13U0ZWxz0jwbjRt3vcGMyF6h7RTH9IUeFU9Cz3adMaAj_BEALw_wcB&matchtype=e&utm_campaign=Python_v.PROF_la.EN_cc.ROWMTA-B_ti.7380&utm_content=deal4584&utm_medium=udemyads&utm_source=adwords&utm_term=_._ag_80869581791_._ad_533995898803_._kw_python+beginners_._de_c_._dm__._pl__._ti_kwd-297920078386_._li_9065291_._pd__._)
 - [JetBrains](https://www.jetbrains.com/academy/?source=google&medium=cpc&campaign=13433860686&keyword=learn%20python%20for%20beginners&gclid=Cj0KCQjw-NaJBhDsARIsAAja6dPKipDg_yOic3YNgnmDnZO2rJbnc26eUsZTgPCm6hmzV5J8LHIe6MgaAtVREALw_wcB)
 - [CodeAcademy](https://www.codecademy.com/pages/learn-python-with-pro?g_network=g&g_device=c&g_adid=518718867549&g_campaign=NL+Language%3A+Basic+-+Exact&g_keyword=intro%20to%20python&g_acctid=243-039-7011&g_adtype=search&g_adgroupid=109376887902&g_keywordid=kwd-300162579586&g_campaignid=11469904505&utm_id=t_kwd-300162579586:ag_109376887902:cp_11469904505:n_g:d_c&utm_term=intro%20to%20python&utm_campaign=NL%20Language%3A%20Basic%20-%20Exact&utm_source=google&utm_medium=paid-search&utm_content=518718867549&hsa_acc=2430397011&hsa_cam=11469904505&hsa_grp=109376887902&hsa_ad=518718867549&hsa_src=g&hsa_tgt=kwd-300162579586&hsa_kw=intro%20to%20python&hsa_mt=e&hsa_net=adwords&hsa_ver=3&gclid=Cj0KCQjw-NaJBhDsARIsAAja6dPmF7yspCRLb8wfuoobk8shT_YIUwY10YsHAIHemAp_o3iKN-Pcs18aAn8UEALw_wcB)

# Bioinformatics

 - [Coursera](https://www.coursera.org/learn/bioconductor)
 - [BioC-workflows](https://www.bioconductor.org/packages/release/workflows/)
 - [metagenomics 1](https://docs.qiime2.org/2021.4/getting-started/)
 - [metagenomics 2](https://huttenhower.sph.harvard.edu/metaphlan/)
 - [metagenomics 3](https://github.com/DerrickWood/kraken2/wiki/Manual)
 
# Statistics

 - [Andy Field](https://www.discovr.rocks/)
 - [DSUR](https://www.discovr.rocks/discovr/)
 - [Biology](https://www.huber.embl.de/msmb/)
 - [ModernDive](https://moderndive.com/)

# Machine Learning and Deep Learnning

 - [Tidymodels](https://www.tidymodels.org/start/)
 - [caret](https://topepo.github.io/caret/)
 - [`{tensorflow}`](https://tensorflow.rstudio.com/tutorials/)
 
# Natural Language Processing

## Tools & packages

 - [spacy](https://spacy.io/)
 - [scikit-learn](https://scikit-learn.org/stable/)

## Model building


## Transformers


## Causal relationships / dependency parsing

 - https://universaldependencies.org/
 - https://doi.org/10.1186/s12911-019-0785-0
 - [Causal Relation Extraction Using Cue Phrase and Lexical Pair Probabilities](http://semanticweb.kaist.ac.kr/home/images/a/af/Causal_Relation_Extraction_Using_Cue_Phrases_and_Lexical_Pair_Probabilities.pdf)
 - [Automatic Extraction of Causal Relations from Natural Language Texts: A Comprehensive Survey](https://arxiv.org/pdf/1605.07895.pdf)
 - [A Survey on Extraction of Causal Relations from Natural Language Text](https://arxiv.org/pdf/2101.06426.pdf)
 - [Toward a Useful Concept of Causality for Lexical Semantics](https://www.isi.edu/~hobbs/causality-jos.pdf)
 


# Live Courses and conferences

 - [BioC](https://bioc2021.bioconductor.org/)
 - [USER!](https://user2021.r-project.org/)
 - [CSAMA](https://www.huber.embl.de/csama2020/)
 
# Books

 - [Applied Predictive Modelling](http://appliedpredictivemodeling.com/)
 - [R Series](https://www.routledge.com/Chapman--HallCRC-The-R-Series/book-series/CRCTHERSER?a=1&pg=4&gclid=Cj0KCQjw-NaJBhDsARIsAAja6dMabjgxY0cxKoZQNDI0e7pdJcqB080chcNsYbVx6vxuwHqGvP8SpWQaAvFzEALw_wcB)
 - [Manning](https://www.manning.com/)



# Graph theory

Look here for examples on communities in graphs 

 - [tidytext](https://www.data-imaginist.com/2017/introducing-tidygraph/)



